# Day 1

In [1]:
!pip install nltk

In [1]:
paragraph = """Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[a] is an Indian politician who is the 14th and current Prime Minister of India since 26 May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.[3]

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.[b] In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[c] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[12] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[d] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[e]"""

In [2]:
paragraph

'Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[a] is an Indian politician who is the 14th and current Prime Minister of India since 26 May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.[3]\n\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he rose through the 

In [3]:
import nltk
from nltk import PorterStemmer
from nltk.corpus import stopwords

## Tokenization: convert paragraph->sentences->words

In [5]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nensi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
sentences=nltk.sent_tokenize(paragraph)
sentences

['Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[a] is an Indian politician who is the 14th and current Prime Minister of India since 26 May 2014.',
 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation.',
 'He is the longest-serving prime minister outside the Indian National Congress.',
 '[3]\n\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.',
 'Modi became a full-time worker for the RSS in Gujarat in 1971.',
 'The RSS assigned him to the BJ

## Stemming

In [7]:
stemmer=PorterStemmer()

In [8]:
#find root word
stemmer.stem('going')

'go'

## Lemmitization

In [9]:
from nltk.stem import WordNetLemmatizer

In [10]:
lemmatizer = WordNetLemmatizer()

In [11]:
#import nltk
#nltk.download()

In [12]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nensi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
lemmatizer.lemmatize('going')

'going'

## Clean Text

In [14]:
# regular expression
import re

In [15]:
corpus=[]
for i in range(len(sentences)):
    text=re.sub('[^a-zA-Z]', ' ', sentences[i])
    text=text.lower()
    corpus.append(text)

corpus

['narendra damodardas modi  gujarati    n  end   d mod   d s  modi      born    september       a  is an indian politician who is the   th and current prime minister of india since    may      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation ',
 'he is the longest serving prime minister outside the indian national congress ',
 '     modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'at the age of     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so ',
 'modi became a full time worker for the rss in gujarat in      ',
 'the rss assigned him to the bjp 

In [16]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

narendra
damodarda
modi
gujarati
n
end
mod
modi
born
septemb
indian
politician
th
current
prime
minist
india
sinc
may
modi
chief
minist
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
longest
serv
prime
minist
outsid
indian
nation
congress
modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
rose
parti
hierarchi
becom
gener
secretari
b
modi
appoint
chief
minist
gujarat
elect
legisl
assembl
soon
administr
consid
complicit
gujarat
riot
c
criticis
manag
crisi
accord
offici
record
littl
peopl
kill
three
quarter
muslim
independ
sourc
estim
death
mostli
muslim
special
investig
team
appoint
suprem
court
india
found
evid
initi
prosecut
proceed
polici
chief
minist
credit
encourag
econom
growth
administr
c

In [17]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [18]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

narendra
damodardas
modi
gujarati
n
end
mod
modi
born
september
indian
politician
th
current
prime
minister
india
since
may
modi
chief
minister
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
longest
serving
prime
minister
outside
indian
national
congress
modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
rose
party
hierarchy
becoming
general
secretary
b
modi
appointed
chief
minister
gujarat
elected
legislative
assembly
soon
administration
considered
complicit
gujarat
riot
c
criticised
management
crisis
according
official
record
little
people
killed
three
quarter
muslim
independent
source
estimated
death
mostly
muslim
special
investigation
team
appointed
supreme
court


## Bag of Words

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True)

In [20]:
X = cv.fit_transform(corpus)

In [21]:
cv.vocabulary_

{'narendra': 90,
 'damodardas': 31,
 'modi': 86,
 'gujarati': 52,
 'end': 40,
 'mod': 85,
 'born': 19,
 'september': 124,
 'is': 70,
 'an': 7,
 'indian': 65,
 'politician': 106,
 'who': 150,
 'the': 137,
 'th': 136,
 'and': 8,
 'current': 30,
 'prime': 108,
 'minister': 84,
 'of': 95,
 'india': 64,
 'since': 127,
 'may': 82,
 'was': 145,
 'chief': 21,
 'gujarat': 51,
 'from': 47,
 'to': 141,
 'member': 83,
 'parliament': 102,
 'mp': 88,
 'for': 44,
 'varanasi': 143,
 'he': 54,
 'bharatiya': 17,
 'janata': 72,
 'party': 103,
 'bjp': 18,
 'rashtriya': 114,
 'swayamsevak': 134,
 'sangh': 121,
 'rss': 120,
 'right': 117,
 'wing': 152,
 'hindu': 59,
 'nationalist': 92,
 'paramilitary': 101,
 'volunteer': 144,
 'organisation': 98,
 'longest': 79,
 'serving': 125,
 'outside': 99,
 'national': 91,
 'congress': 24,
 'raised': 113,
 'in': 62,
 'vadnagar': 142,
 'northeastern': 94,
 'where': 148,
 'completed': 22,
 'his': 60,
 'secondary': 122,
 'education': 36,
 'introduced': 68,
 'at': 13,
 'ag

In [22]:
corpus[0]

'narendra damodardas modi  gujarati    n  end   d mod   d s  modi      born    september       a  is an indian politician who is the   th and current prime minister of india since    may      '

In [23]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]],
      dtype=int64)

In [24]:
# Apply stopwords lemmatize
import re
corpus =[]
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [30]:
corpus

['narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may',
 'modi chief minister gujarat member parliament mp varanasi',
 'member bharatiya janata party bjp rashtriya swayamsevak sangh r right wing hindu nationalist paramilitary volunteer organisation',
 'longest serving prime minister outside indian national congress',
 'modi born raised vadnagar northeastern gujarat completed secondary education',
 'introduced r age eight',
 'age married jashodaben modi abandoned soon publicly acknowledging four decade later legally required',
 'modi became full time worker r gujarat',
 'r assigned bjp rose party hierarchy becoming general secretary',
 'b modi appointed chief minister gujarat elected legislative assembly soon',
 'administration considered complicit gujarat riot c criticised management crisis',
 'according official record little people killed three quarter muslim independent source estimated death mostly muslim',
 's

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True)

In [26]:
x = cv.fit_transform(corpus)

In [27]:
cv.vocabulary_

{'narendra': 71,
 'damodardas': 23,
 'modi': 67,
 'gujarati': 41,
 'end': 31,
 'mod': 66,
 'born': 12,
 'september': 100,
 'indian': 49,
 'politician': 83,
 'th': 111,
 'current': 22,
 'prime': 85,
 'minister': 65,
 'india': 48,
 'since': 103,
 'may': 63,
 'chief': 13,
 'gujarat': 40,
 'member': 64,
 'parliament': 79,
 'mp': 69,
 'varanasi': 115,
 'bharatiya': 10,
 'janata': 53,
 'party': 80,
 'bjp': 11,
 'rashtriya': 91,
 'swayamsevak': 109,
 'sangh': 97,
 'right': 94,
 'wing': 117,
 'hindu': 44,
 'nationalist': 73,
 'paramilitary': 78,
 'volunteer': 116,
 'organisation': 76,
 'longest': 60,
 'serving': 101,
 'outside': 77,
 'national': 72,
 'congress': 16,
 'raised': 90,
 'vadnagar': 114,
 'northeastern': 74,
 'completed': 14,
 'secondary': 98,
 'education': 27,
 'introduced': 51,
 'age': 4,
 'eight': 28,
 'married': 62,
 'jashodaben': 54,
 'abandoned': 0,
 'soon': 104,
 'publicly': 88,
 'acknowledging': 2,
 'four': 36,
 'decade': 25,
 'later': 56,
 'legally': 57,
 'required': 93,
 '

In [28]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may'

In [29]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

# Day 2

## N-Grams

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True, ngram_range=(3,3))

In [32]:
x = cv.fit_transform(corpus)

In [33]:
cv.vocabulary_

{'narendra damodardas modi': 82,
 'damodardas modi gujarati': 26,
 'modi gujarati end': 80,
 'gujarati end mod': 45,
 'end mod modi': 33,
 'mod modi born': 73,
 'modi born september': 78,
 'born september indian': 15,
 'september indian politician': 106,
 'indian politician th': 54,
 'politician th current': 93,
 'th current prime': 115,
 'current prime minister': 25,
 'prime minister india': 95,
 'minister india since': 71,
 'india since may': 52,
 'modi chief minister': 79,
 'chief minister gujarat': 17,
 'minister gujarat member': 70,
 'gujarat member parliament': 43,
 'member parliament mp': 67,
 'parliament mp varanasi': 88,
 'member bharatiya janata': 66,
 'bharatiya janata party': 11,
 'janata party bjp': 58,
 'party bjp rashtriya': 89,
 'bjp rashtriya swayamsevak': 12,
 'rashtriya swayamsevak sangh': 100,
 'swayamsevak sangh right': 113,
 'sangh right wing': 105,
 'right wing hindu': 102,
 'wing hindu nationalist': 119,
 'hindu nationalist paramilitary': 48,
 'nationalist param

In [37]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may'

In [38]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True, ngram_range=(2,3))

In [35]:
x = cv.fit_transform(corpus)

In [36]:
cv.vocabulary_

{'narendra damodardas': 169,
 'damodardas modi': 53,
 'modi gujarati': 163,
 'gujarati end': 92,
 'end mod': 67,
 'mod modi': 150,
 'modi born': 158,
 'born september': 32,
 'september indian': 219,
 'indian politician': 111,
 'politician th': 192,
 'th current': 238,
 'current prime': 51,
 'prime minister': 196,
 'minister india': 146,
 'india since': 107,
 'since may': 225,
 'narendra damodardas modi': 170,
 'damodardas modi gujarati': 54,
 'modi gujarati end': 164,
 'gujarati end mod': 93,
 'end mod modi': 68,
 'mod modi born': 151,
 'modi born september': 160,
 'born september indian': 33,
 'september indian politician': 220,
 'indian politician th': 112,
 'politician th current': 193,
 'th current prime': 239,
 'current prime minister': 52,
 'prime minister india': 197,
 'minister india since': 147,
 'india since may': 108,
 'modi chief': 161,
 'chief minister': 34,
 'minister gujarat': 143,
 'gujarat member': 88,
 'member parliament': 139,
 'parliament mp': 182,
 'mp varanasi': 1

In [39]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may'

In [40]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## TF-IDF

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
cv=TfidfVectorizer()

In [43]:
x=cv.fit_transform(corpus)

In [44]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may'

In [45]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.21819557, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.25128139, 0.25128139, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.25128139, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.25128139, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.21819557, 0.21819557,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.25128139, 0.        ,
        0.161635  , 0.25128139, 0.29811271, 0.        , 0.        ,
        0.        , 0.25128139, 0.        , 0.  

In [46]:
cv=TfidfVectorizer(ngram_range=(3,3))

In [47]:
x=cv.fit_transform(corpus)

In [48]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september indian politician th current prime minister india since may'

In [49]:
x[0].toarray()

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
        0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ]])

In [57]:
# only consider the top max_featyres ordered by term frequency across the corpus 
cv=TfidfVectorizer(ngram_range=(3,3), max_features=10)

In [58]:
x=cv.fit_transform(corpus)

In [59]:
x[0].toarray()

array([[0.        , 0.        , 0.70710678, 0.        , 0.70710678,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

# Day 3

In [1]:
!pip install gensim

     ---------------------------------------- 60.3/60.3 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 14.8/14.8 MB 1.0 MB/s eta 0:00:00
     ---------------------------------------- 42.5/42.5 MB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20448 sha256=6377c58b9caa23482ad1f1804a9f069ddcd11f0734908701401fc6ffcaaea993
  Stored in directory: c:\users\nensi\appdata\local\pip\cache\wheels\01\02\ee\df0699282986903a384b69aab4413af9efd26b3612b5dccc9e
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3522 sha256=eb593b7a786b404174bc4e9cd91bcab59237461e84773f36aea4662e97ac4288
  Stored in directory: c:\users\nensi\appdata\local\pip\cache\wheels\43\aa\48\5c66b931ff013ad19774081aa19656637af5c0cc33b549

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\nensi\\anaconda3\\Lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp310-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

In [4]:
import gensim.downloader as api

In [5]:
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
wv.most_similar('main')

[('biggest', 0.5816999673843384),
 ('key', 0.539416491985321),
 ('major', 0.5380213856697083),
 ('sole', 0.5147795081138611),
 ('primary', 0.5129422545433044),
 ('themain', 0.49124675989151),
 ('twofold', 0.48860183358192444),
 ('predominant', 0.47533175349235535),
 ('central', 0.4368126690387726),
 ('ostensible', 0.4211655259132385)]

In [8]:
wv.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [9]:
wv.similarity('man', 'king')

0.22942673

In [10]:
wv.similarity('html', 'programmer')

0.25811526

In [11]:
vec = wv['king']-wv['man']+wv['woman']
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

# Day 4

In [1]:
import pandas as pd
import numpy as np

In [2]:
message = pd.read_csv("spam.csv", encoding='ISO-8859-1')
message

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
df = message.drop(columns = ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.shape

(5572, 2)

In [5]:
df['v2'].loc[100]

'Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx'

In [6]:
# data cleaning and preprocessing
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nensi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [8]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['v2'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [10]:
# creating the bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, binary=True)
X = cv.fit_transform(corpus).toarray()

In [11]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
X.shape

(5572, 2500)

In [13]:
Y = pd.get_dummies(df['v2'])
Y = Y.iloc[:,1].values
Y

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [14]:
# train test split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [15]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [17]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train, y_train)

In [18]:
y_pred = spam_detect_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [19]:
from sklearn.metrics import accuracy_score, classification_report

In [20]:
score = accuracy_score(y_test, y_pred)
score

1.0

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1115

    accuracy                           1.00      1115
   macro avg       1.00      1.00      1.00      1115
weighted avg       1.00      1.00      1.00      1115



In [22]:
# Creating the TFIDF model

from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X = tv.fit_transform(corpus).toarray()

In [23]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)

In [24]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [25]:
#prediction
y_pred = spam_detect_model.predict(X_test)

In [26]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9991031390134529


In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1115
           1       0.00      0.00      0.00         0

    accuracy                           1.00      1115
   macro avg       0.50      0.50      0.50      1115
weighted avg       1.00      1.00      1.00      1115



C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

RandomForestClassifier()

In [29]:
y_pred = classifier.predict(x_test)

In [30]:
print(accuracy_score(y_pred, y_test))

0.9991031390134529


In [31]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1115
           1       0.00      0.00      0.00         0

    accuracy                           1.00      1115
   macro avg       0.50      0.50      0.50      1115
weighted avg       1.00      1.00      1.00      1115



C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Word2vec Implementation

In [32]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [33]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['v2'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [34]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [35]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [36]:
# lower each words
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [37]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [38]:
import gensim

In [39]:
model = gensim.models.Word2Vec(words, window=5, min_count=2)

In [40]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'text',
 'love',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'home',
 'stop',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'pls',
 'please',
 'co',
 'msg',
 'min',
 'make',
 'dear',
 'night',
 'message',
 'say',
 'well',
 'thing',
 'much',
 'claim',
 'great',
 'oh',
 'hope',
 'hey',
 'number',
 'wat',
 'friend',
 'happy',
 'work',
 'give',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'said',
 'cash',
 'win',
 'yeah',
 'really',
 'amp',
 'life',
 'babe',
 'im',
 'meet',
 'find',
 'morning',
 'uk',
 'last',
 'miss',
 'thanks',
 'year',
 'service',
 'would',
 'com',
 'also',
 'anything',
 'nokia',
 'lol',
 'care',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'contact',
 'urgent',
 'sent',


In [41]:
model.corpus_count

5564

In [42]:
model.epochs

5

In [43]:
model.wv.similar_by_word('kid')

[('see', 0.9973301291465759),
 ('done', 0.9973235726356506),
 ('amp', 0.9972008466720581),
 ('think', 0.9971722364425659),
 ('week', 0.9971405863761902),
 ('com', 0.9971073269844055),
 ('love', 0.9970501661300659),
 ('msg', 0.9970423579216003),
 ('make', 0.9970422387123108),
 ('lor', 0.9970321655273438)]

In [44]:
model.wv['kid'].shape

(100,)

In [45]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [46]:
# !pip install tqdm

In [47]:
from tqdm import tqdm

In [48]:
words[73]

['performed']

In [49]:
type(model.wv.index_to_key)

list

In [50]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [51]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    print("Hello",i)
    X.append(avg_word2vec(words[i]))

  0%|                                                                                         | 0/5564 [00:00<?, ?it/s]C:\Users\nensi\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\nensi\anaconda3\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
  6%|████▌                                                                        | 332/5564 [00:00<00:01, 3307.13it/s]

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110


 25%|███████████████████▏                                                        | 1403/5564 [00:00<00:01, 3511.74it/s]

Hello 656
Hello 657
Hello 658
Hello 659
Hello 660
Hello 661
Hello 662
Hello 663
Hello 664
Hello 665
Hello 666
Hello 667
Hello 668
Hello 669
Hello 670
Hello 671
Hello 672
Hello 673
Hello 674
Hello 675
Hello 676
Hello 677
Hello 678
Hello 679
Hello 680
Hello 681
Hello 682
Hello 683
Hello 684
Hello 685
Hello 686
Hello 687
Hello 688
Hello 689
Hello 690
Hello 691
Hello 692
Hello 693
Hello 694
Hello 695
Hello 696
Hello 697
Hello 698
Hello 699
Hello 700
Hello 701
Hello 702
Hello 703
Hello 704
Hello 705
Hello 706
Hello 707
Hello 708
Hello 709
Hello 710
Hello 711
Hello 712
Hello 713
Hello 714
Hello 715
Hello 716
Hello 717
Hello 718
Hello 719
Hello 720
Hello 721
Hello 722
Hello 723
Hello 724
Hello 725
Hello 726
Hello 727
Hello 728
Hello 729
Hello 730
Hello 731
Hello 732
Hello 733
Hello 734
Hello 735
Hello 736
Hello 737
Hello 738
Hello 739
Hello 740
Hello 741
Hello 742
Hello 743
Hello 744
Hello 745
Hello 746
Hello 747
Hello 748
Hello 749
Hello 750
Hello 751
Hello 752
Hello 753
Hello 754
Hello 755


 38%|█████████████████████████████                                               | 2131/5564 [00:00<00:00, 3580.71it/s]

Hello 1403
Hello 1404
Hello 1405
Hello 1406
Hello 1407
Hello 1408
Hello 1409
Hello 1410
Hello 1411
Hello 1412
Hello 1413
Hello 1414
Hello 1415
Hello 1416
Hello 1417
Hello 1418
Hello 1419
Hello 1420
Hello 1421
Hello 1422
Hello 1423
Hello 1424
Hello 1425
Hello 1426
Hello 1427
Hello 1428
Hello 1429
Hello 1430
Hello 1431
Hello 1432
Hello 1433
Hello 1434
Hello 1435
Hello 1436
Hello 1437
Hello 1438
Hello 1439
Hello 1440
Hello 1441
Hello 1442
Hello 1443
Hello 1444
Hello 1445
Hello 1446
Hello 1447
Hello 1448
Hello 1449
Hello 1450
Hello 1451
Hello 1452
Hello 1453
Hello 1454
Hello 1455
Hello 1456
Hello 1457
Hello 1458
Hello 1459
Hello 1460
Hello 1461
Hello 1462
Hello 1463
Hello 1464
Hello 1465
Hello 1466
Hello 1467
Hello 1468
Hello 1469
Hello 1470
Hello 1471
Hello 1472
Hello 1473
Hello 1474
Hello 1475
Hello 1476
Hello 1477
Hello 1478
Hello 1479
Hello 1480
Hello 1481
Hello 1482
Hello 1483
Hello 1484
Hello 1485
Hello 1486
Hello 1487
Hello 1488
Hello 1489
Hello 1490
Hello 1491
Hello 1492
Hello 1493

 52%|███████████████████████████████████████▏                                    | 2871/5564 [00:00<00:00, 3608.73it/s]

Hello 2131
Hello 2132
Hello 2133
Hello 2134
Hello 2135
Hello 2136
Hello 2137
Hello 2138
Hello 2139
Hello 2140
Hello 2141
Hello 2142
Hello 2143
Hello 2144
Hello 2145
Hello 2146
Hello 2147
Hello 2148
Hello 2149
Hello 2150
Hello 2151
Hello 2152
Hello 2153
Hello 2154
Hello 2155
Hello 2156
Hello 2157
Hello 2158
Hello 2159
Hello 2160
Hello 2161
Hello 2162
Hello 2163
Hello 2164
Hello 2165
Hello 2166
Hello 2167
Hello 2168
Hello 2169
Hello 2170
Hello 2171
Hello 2172
Hello 2173
Hello 2174
Hello 2175
Hello 2176
Hello 2177
Hello 2178
Hello 2179
Hello 2180
Hello 2181
Hello 2182
Hello 2183
Hello 2184
Hello 2185
Hello 2186
Hello 2187
Hello 2188
Hello 2189
Hello 2190
Hello 2191
Hello 2192
Hello 2193
Hello 2194
Hello 2195
Hello 2196
Hello 2197
Hello 2198
Hello 2199
Hello 2200
Hello 2201
Hello 2202
Hello 2203
Hello 2204
Hello 2205
Hello 2206
Hello 2207
Hello 2208
Hello 2209
Hello 2210
Hello 2211
Hello 2212
Hello 2213
Hello 2214
Hello 2215
Hello 2216
Hello 2217
Hello 2218
Hello 2219
Hello 2220
Hello 2221

 58%|████████████████████████████████████████████▎                               | 3242/5564 [00:00<00:00, 3638.79it/s]

Hello 2902
Hello 2903
Hello 2904
Hello 2905
Hello 2906
Hello 2907
Hello 2908
Hello 2909
Hello 2910
Hello 2911
Hello 2912
Hello 2913
Hello 2914
Hello 2915
Hello 2916
Hello 2917
Hello 2918
Hello 2919
Hello 2920
Hello 2921
Hello 2922
Hello 2923
Hello 2924
Hello 2925
Hello 2926
Hello 2927
Hello 2928
Hello 2929
Hello 2930
Hello 2931
Hello 2932
Hello 2933
Hello 2934
Hello 2935
Hello 2936
Hello 2937
Hello 2938
Hello 2939
Hello 2940
Hello 2941
Hello 2942
Hello 2943
Hello 2944
Hello 2945
Hello 2946
Hello 2947
Hello 2948
Hello 2949
Hello 2950
Hello 2951
Hello 2952
Hello 2953
Hello 2954
Hello 2955
Hello 2956
Hello 2957
Hello 2958
Hello 2959
Hello 2960
Hello 2961
Hello 2962
Hello 2963
Hello 2964
Hello 2965
Hello 2966
Hello 2967
Hello 2968
Hello 2969
Hello 2970
Hello 2971
Hello 2972
Hello 2973
Hello 2974
Hello 2975
Hello 2976
Hello 2977
Hello 2978
Hello 2979
Hello 2980
Hello 2981
Hello 2982
Hello 2983
Hello 2984
Hello 2985
Hello 2986
Hello 2987
Hello 2988
Hello 2989
Hello 2990
Hello 2991
Hello 2992

 71%|██████████████████████████████████████████████████████▏                     | 3968/5564 [00:01<00:00, 3593.86it/s]

Hello 3585
Hello 3586
Hello 3587
Hello 3588
Hello 3589
Hello 3590
Hello 3591
Hello 3592
Hello 3593
Hello 3594
Hello 3595
Hello 3596
Hello 3597
Hello 3598
Hello 3599
Hello 3600
Hello 3601
Hello 3602
Hello 3603
Hello 3604
Hello 3605
Hello 3606
Hello 3607
Hello 3608
Hello 3609
Hello 3610
Hello 3611
Hello 3612
Hello 3613
Hello 3614
Hello 3615
Hello 3616
Hello 3617
Hello 3618
Hello 3619
Hello 3620
Hello 3621
Hello 3622
Hello 3623
Hello 3624
Hello 3625
Hello 3626
Hello 3627
Hello 3628
Hello 3629
Hello 3630
Hello 3631
Hello 3632
Hello 3633
Hello 3634
Hello 3635
Hello 3636
Hello 3637
Hello 3638
Hello 3639
Hello 3640
Hello 3641
Hello 3642
Hello 3643
Hello 3644
Hello 3645
Hello 3646
Hello 3647
Hello 3648
Hello 3649
Hello 3650
Hello 3651
Hello 3652
Hello 3653
Hello 3654
Hello 3655
Hello 3656
Hello 3657
Hello 3658
Hello 3659
Hello 3660
Hello 3661
Hello 3662
Hello 3663
Hello 3664
Hello 3665
Hello 3666
Hello 3667
Hello 3668
Hello 3669
Hello 3670
Hello 3671
Hello 3672
Hello 3673
Hello 3674
Hello 3675

 91%|█████████████████████████████████████████████████████████████████████▏      | 5064/5564 [00:01<00:00, 3556.29it/s]

Hello 4301
Hello 4302
Hello 4303
Hello 4304
Hello 4305
Hello 4306
Hello 4307
Hello 4308
Hello 4309
Hello 4310
Hello 4311
Hello 4312
Hello 4313
Hello 4314
Hello 4315
Hello 4316
Hello 4317
Hello 4318
Hello 4319
Hello 4320
Hello 4321
Hello 4322
Hello 4323
Hello 4324
Hello 4325
Hello 4326
Hello 4327
Hello 4328
Hello 4329
Hello 4330
Hello 4331
Hello 4332
Hello 4333
Hello 4334
Hello 4335
Hello 4336
Hello 4337
Hello 4338
Hello 4339
Hello 4340
Hello 4341
Hello 4342
Hello 4343
Hello 4344
Hello 4345
Hello 4346
Hello 4347
Hello 4348
Hello 4349
Hello 4350
Hello 4351
Hello 4352
Hello 4353
Hello 4354
Hello 4355
Hello 4356
Hello 4357
Hello 4358
Hello 4359
Hello 4360
Hello 4361
Hello 4362
Hello 4363
Hello 4364
Hello 4365
Hello 4366
Hello 4367
Hello 4368
Hello 4369
Hello 4370
Hello 4371
Hello 4372
Hello 4373
Hello 4374
Hello 4375
Hello 4376
Hello 4377
Hello 4378
Hello 4379
Hello 4380
Hello 4381
Hello 4382
Hello 4383
Hello 4384
Hello 4385
Hello 4386
Hello 4387
Hello 4388
Hello 4389
Hello 4390
Hello 4391

100%|████████████████████████████████████████████████████████████████████████████| 5564/5564 [00:01<00:00, 3525.59it/s]

Hello 5064
Hello 5065
Hello 5066
Hello 5067
Hello 5068
Hello 5069
Hello 5070
Hello 5071
Hello 5072
Hello 5073
Hello 5074
Hello 5075
Hello 5076
Hello 5077
Hello 5078
Hello 5079
Hello 5080
Hello 5081
Hello 5082
Hello 5083
Hello 5084
Hello 5085
Hello 5086
Hello 5087
Hello 5088
Hello 5089
Hello 5090
Hello 5091
Hello 5092
Hello 5093
Hello 5094
Hello 5095
Hello 5096
Hello 5097
Hello 5098
Hello 5099
Hello 5100
Hello 5101
Hello 5102
Hello 5103
Hello 5104
Hello 5105
Hello 5106
Hello 5107
Hello 5108
Hello 5109
Hello 5110
Hello 5111
Hello 5112
Hello 5113
Hello 5114
Hello 5115
Hello 5116
Hello 5117
Hello 5118
Hello 5119
Hello 5120
Hello 5121
Hello 5122
Hello 5123
Hello 5124
Hello 5125
Hello 5126
Hello 5127
Hello 5128
Hello 5129
Hello 5130
Hello 5131
Hello 5132
Hello 5133
Hello 5134
Hello 5135
Hello 5136
Hello 5137
Hello 5138
Hello 5139
Hello 5140
Hello 5141
Hello 5142
Hello 5143
Hello 5144
Hello 5145
Hello 5146
Hello 5147
Hello 5148
Hello 5149
Hello 5150
Hello 5151
Hello 5152
Hello 5153
Hello 5154

In [52]:
X_new = np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5564,) + inhomogeneous part.

In [56]:
print(X[:5])  # Print the first few elements of X to inspect its structure.

[array([-0.13742329,  0.23760907,  0.08908644, -0.04074125,  0.07361382,
       -0.39668155,  0.10918819,  0.5278267 , -0.18991543, -0.10470584,
       -0.06511195, -0.44535267, -0.01608709,  0.08872262, -0.02300252,
       -0.20710681,  0.05264468, -0.31852233, -0.02812407, -0.47177896,
        0.13338657,  0.12303782,  0.11681465, -0.11075958, -0.08943883,
        0.02566373, -0.13330822, -0.19824462, -0.2004506 ,  0.05500232,
        0.28683454,  0.09198216,  0.04904387, -0.18442838, -0.10465036,
        0.26310667, -0.00627228, -0.23751211, -0.11744472, -0.3777707 ,
       -0.00692717, -0.2502705 , -0.01953581,  0.00736942,  0.21961753,
       -0.05189565, -0.16222647,  0.02977468,  0.10898063,  0.12988038,
        0.15783237, -0.22534204, -0.06088391, -0.03774434, -0.19283217,
        0.13864337,  0.14427085, -0.02020812, -0.30131936,  0.07640042,
        0.0812503 ,  0.05104673, -0.06008573,  0.01364946, -0.32099995,
        0.19454575,  0.19460131,  0.18563432, -0.33311787,  0.3

# Day 5

## Word Embedding Techniques using Embedding Layer in Keras

In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Vocabulary size
voc_size=500

### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[281, 317, 266, 264], [281, 317, 266, 71], [281, 235, 266, 321], [277, 456, 276, 46, 52], [277, 456, 276, 46, 60], [186, 281, 275, 266, 399], [325, 292, 443, 46]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
# pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 281 317 266 264]
 [  0   0   0   0 281 317 266  71]
 [  0   0   0   0 281 235 266 321]
 [  0   0   0 277 456 276  46  52]
 [  0   0   0 277 456 276  46  60]
 [  0   0   0 186 281 275 266 399]
 [  0   0   0   0 325 292 443  46]]


In [10]:
# 10 feature dimesnions
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 281, 317, 266, 264])

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[[-0.04708065,  0.04712698, -0.02781906, -0.02107023,
          0.02759773,  0.03906992,  0.03584364,  0.0132441 ,
         -0.01313642, -0.00555   ],
        [-0.04708065,  0.04712698, -0.02781906, -0.02107023,
          0.02759773,  0.03906992,  0.03584364,  0.0132441 ,
         -0.01313642, -0.00555   ],
        [-0.04708065,  0.04712698, -0.02781906, -0.02107023,
          0.02759773,  0.03906992,  0.03584364,  0.0132441 ,
         -0.01313642, -0.00555   ],
        [-0.04708065,  0.04712698, -0.02781906, -0.02107023,
          0.02759773,  0.03906992,  0.03584364,  0.0132441 ,
         -0.01313642, -0.00555   ],
        [-0.03254407, -0.04423866,  0.02622325,  0.00664058,
          0.04840169, -0.01077934, -0.02432039, -0.02853273,
          0.00422822,  0.03544861],
        [ 0.01504935, -0.03839771, -0.01546078, -0.00046352,
          0.04322144, -0.04228161, -0.02863896, -0.0126721 ,
         -0.00632212,  0.00941688],
        [-0.01215263, -0.00066491, -0.03848376, -0.0

In [21]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[[-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773
    0.03906992  0.03584364  0.0132441  -0.01313642 -0.00555   ]
  [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773
    0.03906992  0.03584364  0.0132441  -0.01313642 -0.00555   ]
  [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773
    0.03906992  0.03584364  0.0132441  -0.01313642 -0.00555   ]
  [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773
    0.03906992  0.03584364  0.0132441  -0.01313642 -0.00555   ]
  [-0.03254407 -0.04423866  0.02622325  0.00664058  0.04840169
   -0.01077934 -0.02432039 -0.02853273  0.00422822  0.03544861]
  [ 0.01504935 -0.03839771 -0.01546078 -0.00046352  0.04322144
   -0.04228161 -0.02863896 -0.0126721  -0.00632212  0.00941688]
  [-0.01215263 -0.00066491 -0.03848376 -0.01721848 -0.02114154
   -0.01287856 -0.03026226  0.03468711  0.04232471 -0.02977922]
  [ 0.00418387  0.0097966   0.0129307   0.03577149 -0.03800581
   -0.0185

In [22]:
embedded_docs[0]

array([  0,   0,   0,   0, 281, 317, 266, 264])

In [23]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773  0.03906992
   0.03584364  0.0132441  -0.01313642 -0.00555   ]
 [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773  0.03906992
   0.03584364  0.0132441  -0.01313642 -0.00555   ]
 [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773  0.03906992
   0.03584364  0.0132441  -0.01313642 -0.00555   ]
 [-0.04708065  0.04712698 -0.02781906 -0.02107023  0.02759773  0.03906992
   0.03584364  0.0132441  -0.01313642 -0.00555   ]
 [-0.03254407 -0.04423866  0.02622325  0.00664058  0.04840169 -0.01077934
  -0.02432039 -0.02853273  0.00422822  0.03544861]
 [ 0.01504935 -0.03839771 -0.01546078 -0.00046352  0.04322144 -0.04228161
  -0.02863896 -0.0126721  -0.00632212  0.00941688]
 [-0.01215263 -0.00066491 -0.03848376 -0.01721848 -0.02114154 -0.01287856
  -0.03026226  0.03468711  0.04232471 -0.02977922]
 [ 0.00418387  0.0097966   0.0129307   0.03577149 -0.03800581 -0.01854292
   0.03767129

# Day 6

# Fake News Classifier Using LSTM

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
# Drop Nan Values
df=df.dropna()

In [7]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [8]:
# Get the Independent Features

X=df.drop('label',axis=1)

In [9]:
# Get the Dependent features
y=df['label']

In [10]:
X.shape

(18285, 4)

In [11]:
y.shape

(18285,)

In [12]:
import tensorflow as tf

In [13]:
tf.__version__

'2.16.1'

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [15]:
### Vocabulary size
voc_size=5000

## Onehot Representation

In [16]:
messages=X.copy()

In [17]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [18]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [19]:
messages.reset_index(inplace=True)

In [20]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nensi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
# Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [24]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [25]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [26]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4362, 3809, 1995, 148, 711, 4557, 2366, 1493, 1201, 2081],
 [1635, 3592, 4680, 866, 12, 130, 3766],
 [992, 990, 4114, 87],
 [1884, 4606, 4438, 2034, 4901, 1221],
 [1324, 12, 843, 4089, 3531, 2972, 12, 3165, 3830, 1479],
 [3101,
  2770,
  3390,
  93,
  701,
  3002,
  3659,
  1924,
  3223,
  2814,
  4919,
  3546,
  3080,
  3124,
  3766],
 [3793, 2861, 2374, 2257, 976, 4863, 4308, 1961, 2446, 3649, 2498],
 [3395, 732, 1868, 2589, 3525, 1986, 3002, 1387, 2446, 3649, 2498],
 [2031, 1281, 2588, 2375, 3402, 3397, 3686, 4312, 3002, 2467],
 [3845, 3444, 244, 3560, 141, 4358, 2228, 138],
 [1389, 1161, 4347, 4614, 275, 406, 4611, 3421, 2881, 3338, 760],
 [2034, 2976, 711, 3397, 3002, 3525],
 [3312, 1417, 2296, 3817, 2398, 64, 2986, 368, 2819],
 [1272, 985, 4185, 3655, 2301, 4598, 577, 2446, 3649, 2498],
 [4064, 743, 2335, 4352, 118, 2446, 3649, 2498],
 [1665, 4274, 1776, 3011, 1435, 1587, 1073, 2305, 4541, 2138],
 [1465, 1855, 3592],
 [3799, 4984, 3747, 2444, 3002, 4323, 987, 3766],
 [1833, 241

In [27]:
onehot_repr[1]

[1635, 3592, 4680, 866, 12, 130, 3766]

## Embedding Representation

In [28]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[4362 3809 1995 ...    0    0    0]
 [1635 3592 4680 ...    0    0    0]
 [ 992  990 4114 ...    0    0    0]
 ...
 [2001  187 3113 ...    0    0    0]
 [2769 3525  446 ...    0    0    0]
 [   4  937 4286 ...    0    0    0]]


In [29]:
embedded_docs[1]

array([1635, 3592, 4680,  866,   12,  130, 3766,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [30]:
# Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

C:\Users\nensi\anaconda3\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [31]:
len(embedded_docs),y.shape

(18285, (18285,))

In [32]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [33]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

## Model Training

In [35]:
# Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.7707 - loss: 0.4160 - val_accuracy: 0.9206 - val_loss: 0.1893
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.9497 - loss: 0.1287 - val_accuracy: 0.9127 - val_loss: 0.2494
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.9704 - loss: 0.0932 - val_accuracy: 0.9142 - val_loss: 0.2791
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9853 - loss: 0.0514 - val_accuracy: 0.9167 - val_loss: 0.2368
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9874 - loss: 0.0460 - val_accuracy: 0.9110 - val_loss: 0.3573
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.9918 - loss: 0.0296 - val_accuracy: 0.9057 - val_loss: 0.3365
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.9922 - loss: 0.0262 - val_accuracy: 0.9087 - val_loss: 0.3376
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.9953 - loss: 0.0202 - val_accu

## Adding Dropout

In [36]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

## Performance Metrics And Accuracy

In [37]:
y_pred=model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [38]:
# AUC ROC Curve
y_pred=np.where(y_pred > 0.6, 1,0)

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      3419
           1       0.00      0.00      0.00      2616

    accuracy                           0.57      6035
   macro avg       0.28      0.50      0.36      6035
weighted avg       0.32      0.57      0.41      6035



C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nensi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
